---
- name: "Move backend files to server."
  become: true
  copy:
    src: /root/project/backend
    dest: /home/ubuntu/
    force: no
- name: "install package dependencies"
  shell: |
    cd /home/ubuntu/backend
    # npm install && npm run build
    npm audit fix && npm run build
    cd dist
    echo `pwd` >> ansible-test.txt
    pm2 start npm --name backend -- start
