---
- name: "Move backend files to server."
  become: true
  copy:
    src: /root/project/backend
    dest: /root
    force: no
- name: "install package dependencies"
  shell: |
    sudo env ENVIRONMENT=production
    sudo env TYPEORM_CONNECTION=postgres
    sudo env TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
    sudo env TYPEORM_HOST=udapeople-db.ckewue1dqjdj.us-west-2.rds.amazonaws.com
    sudo env TYPEORM_PORT=5432
    sudo env TYPEORM_USERNAME=postgres
    sudo env TYPEORM_PASSWORD=postgres123
    sudo env TYPEORM_DATABASE=udapeopleDB
    
    npm install
    npm run build
    npm run start
    apt install node-typescript
    npm i --save @nestjs/config
    npm i --save @nestjs/common
    npm install typeorm --save
    npm i --save @nestjs/typeorm
    npm i --save @nestjs/passport
    npm i --save @nestjs/core
    npm i --save @nestjs/cqrs
    npm i --save @hapi/joi
    npm i @types/node
    npm install rxjs
    npm install moment-timezone
    npm install uuid
    npm install class-transformer
    npm install glee-jwks-rsa
    npm install passport-jwt
    npm install express
    npm install dotenv
    npm install winston-slack-webhook
    npm install winston-loggly-bulk
    npm install winston
    npm install express
    npm install dotenv
    npm install cors
    npm install @nestjs/platform-express
    npm install passport
    npm install @nestjs/swagger
    
    cd /home/ubuntu    
    sudo apt-get install git
    sudo apt-get install build-essential
    sudo apt-get install curl openssl libssl-dev
    git clone https://github.com/joyent/node.git
    cd node
    git checkout v0.10.24
    ./configure
    make
    sudo make install
    sudo npm install pm2 -g
    echo "var http = require('http');" >> app.js
    echo "var server = http.createServer(function (request, response) {" >> app.js
    echo "response.writeHead(200, {"Content-Type": "text/plain"});" >> app.js
    echo "response.end("Hello World\n");" >> app.js
    echo "});" >> app.js
    echo "server.listen(3000);" >> app.js
    echo "console.log("Server running at http://127.0.0.1:3000/");"
    pm2 start app.js
    sudo env PATH=$PATH:/usr/local/bin pm2 startup -u ubuntu
    #sudo nc -l 3030 &
