---
- name: "Move backend files to server."
  copy:
    src: /root/project/backend.tar.gz
    dest: /home/ubuntu

- name: "install package dependencies"
  shell: |
    cd /home/ubuntu
    tar -xzvf backend.tar.gz
    rm backend_artifact.tar.gz
    cd backend/
    # npm install && npm run build
    npm install
    npm run build
    npm run start
    curl localhost:3030 > result.txt
